import test from "node:test";
import assert from "node:assert/strict";
import { encodeAbiParameters } from "viem";
import { createFinancialExecutionAdapterEngine, listFinancialExecutionAdapterDescriptors, PANCAKE_V3_SWAP_ROUTER } from "./index.js";
import type { MarketplaceActivation, MarketplaceServiceRecord, PermissionCheckoutScope, ScopedPermissionRequest, ServiceCategory } from "@spotriq/domain";

const buyer="0x1111111111111111111111111111111111111111";
const poolAddress="0x2222222222222222222222222222222222222222";
const token0="0x3333333333333333333333333333333333333333";
const token1="0x4444444444444444444444444444444444444444";
const venusMarket="0x5555555555555555555555555555555555555555";
const venusAsset="0x6666666666666666666666666666666666666666";
const factory="0x7777777777777777777777777777777777777777";
const future=()=>new Date(Date.now()+3_600_000).toISOString();

function activation(serviceId:string):MarketplaceActivation{return{activationId:`activation:${serviceId}`,hireId:"hire:1",quoteId:"quote:1",serviceId,buyerAddress:buyer,buyerChainId:97,serviceChainId:97,state:"ACTIVE",activationKind:"READ_ONLY_SERVICE_RELATIONSHIP",termsSnapshot:{termsVersion:"1",commercialModel:"FREE",serviceType:"READ_ONLY_SERVICE",price:{amount:"0",currency:"USD"},network:"BSC",chainId:97,paymentRail:"FREE",scope:{summary:"read",protocols:[serviceId.includes("grid")?"PancakeSwap":"Venus"],financialAuthorityRequired:false,walletSigningRequired:false},availability:"AVAILABLE",quoteValiditySeconds:300},termsHash:"0x1",paymentRequired:false,permissionRequired:false,walletSigningAuthorityGranted:false,financialExecutionAuthorityGranted:false,idempotencyKey:"k",activatedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),methodVersion:"test",evidence:[],limitations:[]};}

function scope(category:ServiceCategory):PermissionCheckoutScope{
  const common={authorityTier:category==="health"?"PROTECTIVE_WRITE" as const:"BOUNDED_FINANCIAL" as const,approvalMode:"ASK_BEFORE_EXECUTION" as const,validForMinutes:60,expiresAt:future(),deniedActions:[],limits:[],categoryContext:{}};
  if(category==="rebalancing")return{...common,category,protocol:"PancakeSwap",jobSummary:"rebalance",target:{positionTokenId:"12490",assetAddresses:[],marketAddresses:[]},allowedActions:["REBALANCE"],limits:[{code:"TOKEN0_SPEND",label:"token0",value:"10",unit:"DISPLAY_AMOUNT",asset:token0,provenance:"user-proposed"},{code:"TOKEN1_SPEND",label:"token1",value:"10",unit:"DISPLAY_AMOUNT",asset:token1,provenance:"user-proposed"}]};
  if(category==="grid")return{...common,category,protocol:"PancakeSwap",jobSummary:"grid",target:{poolAddress,assetAddresses:[token0],marketAddresses:[]},allowedActions:["GRID_SWAP_EXACT_INPUT_SINGLE"],limits:[{code:"CAPITAL",label:"capital",value:"10",unit:"DISPLAY_AMOUNT",asset:token0,provenance:"user-proposed"},{code:"SINGLE_ACTION",label:"single",value:"2",unit:"DISPLAY_AMOUNT",asset:token0,provenance:"user-proposed"}]};
  if(category==="yield")return{...common,category,protocol:"Venus",jobSummary:"yield",target:{assetAddresses:[venusAsset],marketAddresses:[venusMarket]},allowedActions:["YIELD_SUPPLY","YIELD_WITHDRAW"],limits:[{code:"CAPITAL",label:"capital",value:"10",unit:"DISPLAY_AMOUNT",asset:venusAsset,provenance:"user-proposed"},{code:"SINGLE_ACTION",label:"single",value:"2",unit:"DISPLAY_AMOUNT",asset:venusAsset,provenance:"user-proposed"}]};
  return{...common,category,protocol:"Venus",jobSummary:"protect",target:{assetAddresses:[venusAsset],marketAddresses:[venusMarket]},allowedActions:["REPAY"],limits:[{code:"INTERVENTION",label:"intervention",value:"2",unit:"DISPLAY_AMOUNT",asset:venusAsset,provenance:"user-proposed"},{code:"HEALTH_TRIGGER",label:"health",value:"1.25",unit:"HEALTH_FACTOR",provenance:"user-proposed"}],categoryContext:{protectiveActions:["REPAY"]}};
}

function request(category:ServiceCategory,serviceId:string,ready=false):ScopedPermissionRequest{return{permissionRequestId:`spr:${category}`,checkoutId:`pc:${category}`,activationId:`activation:${serviceId}`,serviceId,buyerAddress:buyer,category,state:ready?"GRANT_RECONCILED":"BLOCKED",authorityTier:category==="health"?"PROTECTIVE_WRITE":"BOUNDED_FINANCIAL",provider:"UNASSIGNED",providerSubmissionState:ready?"RECONCILED":"BLOCKED",scopeSnapshot:scope(category),scopeHash:"0x2",blockers:[],permissionGrantId:ready?`grant:${category}`:undefined,reviewedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),expiresAt:future(),methodVersion:"test",limitations:[]};}

function record(serviceId:string,category:ServiceCategory,ready=false){return{service:{serviceId,agentId:serviceId,name:serviceId,slug:serviceId,category,description:"",readiness:ready?"READY":"TESTNET_ONLY",permissionIntensity:ready?"bounded":"read-only",pricing:{model:"FREE",amount:"0",protocolCostsNote:""},supportedProtocols:[category==="grid"||category==="rebalancing"?"PancakeSwap":"Venus"],automationMode:ready?"AUTOMATIC_WITH_LIMITS":"READ_ONLY",evidenceSummary:{marketplaceObserved:"",testsPassed:1},operator:"Spotriq",erc8004Verified:true,marketplaceActivationEligible:ready},permissionProfile:{permissionProfileId:"pp",serviceId,protocols:[category==="grid"||category==="rebalancing"?"PancakeSwap":"Venus"],assets:[],executionMode:ready?"AUTOMATIC_WITH_LIMITS":"READ_ONLY",declarationState:"DECLARED",intensity:ready?"bounded":"read-only",provenance:"marketplace-observed"},readiness:{readinessSnapshotId:"r",serviceId,state:ready?"READY":"TESTNET_ONLY",checkedAt:new Date().toISOString(),reasons:[]},offer:{offerId:"o",serviceId,state:"AVAILABLE",source:"marketplace-observed",note:""},listing:{listingId:"l",agentId:serviceId,slug:serviceId,name:serviceId,shortDescription:"",categoryTags:[category],status:"ACTIVE"},capabilityClaims:[],evidence:[],tests:{serviceId,state:"PASSED",lastRunAt:new Date().toISOString(),tests:[],limitations:[]}} as unknown as MarketplaceServiceRecord;}

function chainMock(){return{network:"testnet",definition:{chainId:97},getBlockNumber:async()=>"100",callContract:async(target:string)=>{const normalized=target.toLowerCase();if(normalized===factory)return{data:encodeAbiParameters([{type:"address"}],[poolAddress]),blockNumber:"100"};if(normalized===venusMarket)return{data:encodeAbiParameters([{type:"address"}],[venusAsset]),blockNumber:"100"};if(normalized===venusAsset)return{data:encodeAbiParameters([{type:"uint8"}],[18]),blockNumber:"100"};throw new Error(`unexpected contract ${target}`);}} as any;}

function engineFor(category:ServiceCategory,ready=false){const serviceId=`svc:reference:${category}`;const req=request(category,serviceId,ready);return{req,engine:createFinancialExecutionAdapterEngine({chain:chainMock(),pancakeSwap:{getStatus:()=>({contracts:{v3Factory:factory}}),getV3Pool:async()=>({poolAddress,token0:{address:token0,decimals:18},token1:{address:token1,decimals:18},feePips:500,blockNumber:"100"})} as any,venus:{getYieldOpportunities:async()=>({opportunities:[{vToken:venusMarket,underlying:{address:venusAsset}}]}),getWalletPositions:async()=>({positions:[{healthFactor:"1.10",markets:[{vToken:venusMarket,collateralEnabled:true}]}]})} as any,commercial:{getActivation:async()=>activation(serviceId)} as any,marketplace:{getService:async()=>record(serviceId,category,ready)} as any,permissionCheckout:{getRequest:async()=>req} as any})};}

test("catalog implements all four category execution adapters",()=>{const adapters=listFinancialExecutionAdapterDescriptors();assert.equal(adapters.length,4);assert.deepEqual(new Set(adapters.map(a=>a.category)),new Set(["rebalancing","grid","yield","health"]));assert.ok(adapters.every(a=>a.state==="IMPLEMENTED"&&a.networkPolicy==="BSC_TESTNET_ONLY"));});

test("current read-only service fails closed before call preparation and persists the guard's fresh preflight",async()=>{const{req,engine}=engineFor("grid",false);const pf=await engine.preflight(req.permissionRequestId,{buyerAddress:buyer});assert.equal(pf.state,"BLOCKED");assert.equal(pf.executionEligible,false);assert.ok(pf.checks.some(c=>c.code==="ADAPTER"&&c.state==="PASS"));assert.ok(pf.checks.some(c=>c.code==="SERVICE_FINANCIAL_READINESS"&&c.state==="FAIL"));assert.ok(pf.checks.some(c=>c.code==="PERMISSION_GRANT"&&c.state==="FAIL"));const report=await engine.guard(req.permissionRequestId,{buyerAddress:buyer,proposal:{category:"grid",action:"GRID_SWAP_EXACT_INPUT_SINGLE",amountIn:"1",amountOutMinimumRaw:"1",deadlineUnix:Math.floor(Date.now()/1000)+300}});assert.equal(report.state,"BLOCKED");assert.equal(report.call,undefined);const state=await engine.getState(req.permissionRequestId);assert.equal(state.latestPreflight?.preflightId,report.preflight.preflightId);assert.equal(state.latestGuard?.guardReportId,report.guardReportId);});

test("eligible Grid scope prepares exact canonical-router calldata but still cannot dispatch",async()=>{const{req,engine}=engineFor("grid",true);const report=await engine.guard(req.permissionRequestId,{buyerAddress:buyer,proposal:{category:"grid",action:"GRID_SWAP_EXACT_INPUT_SINGLE",amountIn:"1",amountOutMinimumRaw:"1",deadlineUnix:Math.floor(Date.now()/1000)+300}});assert.equal(report.state,"PASS_BUT_EXECUTION_BLOCKED");assert.equal(report.executionEligible,false);assert.equal(report.call?.to,PANCAKE_V3_SWAP_ROUTER.testnet.toLowerCase());assert.equal(report.call?.functionName,"exactInputSingle");assert.equal(report.call?.decodedArguments.tokenIn,token0);assert.equal(report.call?.decodedArguments.tokenOut,token1);});

test("eligible Yield scope prepares only canonical Venus vToken supply calldata and remains non-dispatchable",async()=>{const{req,engine}=engineFor("yield",true);const report=await engine.guard(req.permissionRequestId,{buyerAddress:buyer,proposal:{category:"yield",action:"YIELD_SUPPLY",marketAddress:venusMarket,amount:"1"}});assert.equal(report.state,"PASS_BUT_EXECUTION_BLOCKED");assert.equal(report.executionEligible,false);assert.equal(report.call?.to,venusMarket);assert.equal(report.call?.functionName,"mint");assert.ok(report.checks.some(c=>c.code==="VENUS_MARKET"&&c.state==="PASS"));});

test("eligible Health scope prepares only trigger-authorized protective repay and remains non-dispatchable",async()=>{const{req,engine}=engineFor("health",true);const report=await engine.guard(req.permissionRequestId,{buyerAddress:buyer,proposal:{category:"health",action:"HEALTH_REPAY",marketAddress:venusMarket,amount:"1"}});assert.equal(report.state,"PASS_BUT_EXECUTION_BLOCKED");assert.equal(report.executionEligible,false);assert.equal(report.call?.to,venusMarket);assert.equal(report.call?.functionName,"repayBorrow");assert.ok(report.checks.some(c=>c.code==="HEALTH_TRIGGER"&&c.state==="PASS"));});
