import React,{useEffect,useState} from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, GitBranch, Info, RefreshCw, ShieldAlert, Wallet } from "lucide-react";
import type { NavState, Route, SmartMoneyPlan, SmartMoneyPlanConflict } from "../domain/types";
import { getActiveCheckMode,getActiveCheckSessionId,smartMoneyRepository } from "../repositories/smartMoneyRepository";
import { smartMoneyPlanRepository } from "../repositories/smartMoneyPlanRepository";

type Navigate=(r:Route,p?:Partial<NavState>)=>void;
const CATS:Record<string,string>={rebalancing:"Rebalancing",grid:"Grid Trading",yield:"Yield Optimisation",health:"Health Factor Monitoring"};
const severityClass=(severity:SmartMoneyPlanConflict["severity"])=>severity==="BLOCK"?"border-[#f87171]/20 bg-[#f87171]/5 text-[#fca5a5]":severity==="WARN"?"border-[#f59e0b]/20 bg-[#f59e0b]/5 text-[#d6a04a]":"border-[#60a5fa]/15 bg-[#60a5fa]/5 text-[#93c5fd]";

function PlanSummary({plan,onOpen}:{plan:SmartMoneyPlan;onOpen:()=>void}){
 return <button onClick={onOpen} className="w-full text-left rounded-xl border border-white/8 bg-[#111722] hover:border-white/14 p-5 transition-colors">
  <div className="flex items-start justify-between gap-4"><div><div className="text-sm font-semibold text-[#dde3ef]">Smart Money Plan</div><div className="text-xs font-mono text-[#52637b] mt-1">{plan.planId}</div></div><span className={plan.state==="BLOCKED"?"text-xs text-[#f87171]":"text-xs text-[#2dd4bf]"}>{plan.state}</span></div>
  <div className="flex flex-wrap gap-2 mt-4">{plan.members.map(m=><span key={m.memberId} className="text-[10px] font-mono px-2 py-1 rounded bg-white/5 text-[#9aacc4]">{CATS[m.category]} · {m.serviceName}</span>)}</div>
  <div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div><span className="text-[#6b7d99]">Blockers</span><div className="text-[#dde3ef] mt-1">{plan.conflictReport.blockingCount}</div></div><div><span className="text-[#6b7d99]">Warnings</span><div className="text-[#dde3ef] mt-1">{plan.conflictReport.warningCount}</div></div><div><span className="text-[#6b7d99]">Authority</span><div className="text-[#dde3ef] mt-1">Independent</div></div></div>
 </button>;
}

export function LivePlansPage({navigate}:{navigate:Navigate}){
 const [buyer,setBuyer]=useState("");const [plans,setPlans]=useState<SmartMoneyPlan[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string>();
 const load=async(address:string)=>{if(!/^0x[0-9a-fA-F]{40}$/.test(address)){setError("Enter a valid BSC wallet address, or run a live Smart Money Check first.");return;}setBusy(true);setError(undefined);try{const state=await smartMoneyPlanRepository.listForBuyer(address);setPlans(state.plans);setBuyer(state.buyerAddress);}catch(e){setError(e instanceof Error?e.message:"Could not load Smart Money Plans.");}finally{setBusy(false);}};
 useEffect(()=>{const sessionId=getActiveCheckSessionId();if(getActiveCheckMode()!=="live"||!sessionId)return;void smartMoneyRepository.getCheck(sessionId).then(check=>void load(check.session.walletAddress)).catch(()=>undefined);},[]);
 return <div className="max-w-5xl mx-auto px-6 py-8 space-y-6"><div><h1 className="text-2xl font-semibold text-[#dde3ef]">Smart Money Plans</h1><p className="text-sm text-[#6b7d99] mt-1">Deterministic combinations of specific findings and specialist AgentServices. Plan ≠ Super-agent.</p></div>
  <div className="rounded-lg border border-[#2dd4bf]/15 bg-[#2dd4bf]/[0.03] p-4 text-xs text-[#9aacc4]"><div className="text-[#2dd4bf] font-medium mb-1">Independent by design</div>Each plan member keeps its own Offer, Activation, PermissionGrant, execution boundary, activity and outcome. Spotriq never creates a shared plan signer.</div>
  <div className="flex gap-2"><div className="relative flex-1"><Wallet className="w-4 h-4 absolute left-3 top-3 text-[#52637b]"/><input value={buyer} onChange={e=>setBuyer(e.target.value)} placeholder="0x… buyer wallet" className="w-full bg-[#111722] border border-white/10 rounded-md pl-9 pr-3 py-2.5 text-sm font-mono text-[#dde3ef]"/></div><button onClick={()=>void load(buyer)} className="px-4 py-2 rounded-md border border-white/10 text-sm text-[#9aacc4] hover:text-[#dde3ef]">{busy?"Loading…":"Load"}</button></div>
  {error&&<div className="rounded-lg border border-[#f87171]/20 bg-[#f87171]/5 p-3 text-sm text-[#fca5a5]">{error}</div>}
  {busy?<div className="flex items-center gap-2 text-sm text-[#6b7d99]"><RefreshCw className="w-4 h-4 animate-spin"/>Loading plans…</div>:plans.length?<div className="grid md:grid-cols-2 gap-4">{plans.map(p=><PlanSummary key={p.planId} plan={p} onOpen={()=>navigate("plan-profile",{planId:p.planId})}/>)}</div>:<div className="rounded-xl border border-white/7 bg-[#111722] p-6 text-sm text-[#6b7d99]">No persisted live plans for this wallet yet. Run a Smart Money Check and choose <span className="text-[#dde3ef]">Build Smart Money Plan</span>.</div>}
 </div>;
}

export function LivePlanProfilePage({planId,navigate}:{planId:string;navigate:Navigate}){
 const [plan,setPlan]=useState<SmartMoneyPlan>();const [error,setError]=useState<string>();
 useEffect(()=>{void smartMoneyPlanRepository.get(planId).then(setPlan).catch(e=>setError(e instanceof Error?e.message:"Could not load Smart Money Plan."));},[planId]);
 if(error)return <div className="max-w-4xl mx-auto px-6 py-10"><div className="rounded-lg border border-[#f87171]/20 bg-[#f87171]/5 p-4 text-sm text-[#fca5a5]">{error}</div></div>;
 if(!plan)return <div className="max-w-4xl mx-auto px-6 py-10 flex items-center gap-2 text-[#6b7d99]"><RefreshCw className="w-4 h-4 animate-spin"/>Loading plan…</div>;
 return <div className="max-w-5xl mx-auto px-6 py-8 space-y-6"><button onClick={()=>navigate("plans")} className="text-xs text-[#6b7d99] hover:text-[#9aacc4] flex items-center gap-1"><ArrowLeft className="w-3 h-3"/>All Plans</button>
  <div className="flex items-start justify-between gap-4"><div><div className="text-xs font-mono uppercase text-[#2dd4bf]">Smart Money Plan · deterministic review</div><h1 className="text-2xl font-semibold text-[#dde3ef] mt-1">{plan.members.length} specialist role{plan.members.length===1?"":"s"}</h1><p className="text-sm text-[#6b7d99] mt-2">{plan.reviewSummary}</p></div><span className={plan.state==="BLOCKED"?"px-2 py-1 rounded bg-[#f87171]/10 text-[#f87171] text-xs":"px-2 py-1 rounded bg-[#2dd4bf]/10 text-[#2dd4bf] text-xs"}>{plan.state}</span></div>
  <div className="grid md:grid-cols-3 gap-3"><div className="rounded-lg border border-white/7 p-4"><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Activation</div><div className="text-sm text-[#dde3ef] mt-1">Independent per service</div></div><div className="rounded-lg border border-white/7 p-4"><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Authority</div><div className="text-sm text-[#dde3ef] mt-1">Independent per service</div></div><div className="rounded-lg border border-white/7 p-4"><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Execution</div><div className="text-sm text-[#dde3ef] mt-1">No shared execution</div></div></div>
  <section><h2 className="text-sm font-semibold text-[#dde3ef] mb-3 flex items-center gap-2"><GitBranch className="w-4 h-4"/>Plan members</h2><div className="space-y-3">{plan.members.map(m=><div key={m.memberId} className="rounded-xl border border-white/7 bg-[#111722] p-5"><div className="flex items-start justify-between gap-3"><div><div className="text-xs text-[#2dd4bf]">{CATS[m.category]}</div><div className="font-medium text-[#dde3ef] mt-1">{m.serviceName}</div><div className="text-xs text-[#6b7d99] mt-1">{m.roleSummary}</div></div><span className="text-[10px] font-mono text-[#9aacc4]">{m.readiness}</span></div><div className="grid sm:grid-cols-3 gap-2 mt-4 text-xs"><div><span className="text-[#52637b]">Match</span><div className="text-[#9aacc4] mt-1">#{m.matchRank} · {m.matchTier.replaceAll("_"," ")}</div></div><div><span className="text-[#52637b]">Authority</span><div className="text-[#9aacc4] mt-1">{m.authorityState.replaceAll("_"," ")}</div></div><div><span className="text-[#52637b]">Relationship</span><div className="text-[#9aacc4] mt-1">{m.existingActivationId?"Already active":"Not active"}</div></div></div><div className="mt-4 flex gap-2"><button onClick={()=>navigate("agent",{agentId:m.serviceId})} className="px-3 py-1.5 rounded-md border border-white/10 text-xs text-[#9aacc4] hover:text-[#dde3ef]">Review service independently</button></div></div>)}</div></section>
  <section><h2 className="text-sm font-semibold text-[#dde3ef] mb-3 flex items-center gap-2"><ShieldAlert className="w-4 h-4"/>Compatibility & conflicts</h2>{plan.conflictReport.conflicts.length?<div className="space-y-2">{plan.conflictReport.conflicts.map(c=><div key={c.conflictId} className={`rounded-lg border p-4 ${severityClass(c.severity)}`}><div className="flex items-start gap-2">{c.severity==="BLOCK"?<AlertTriangle className="w-4 h-4 mt-0.5 shrink-0"/>:c.severity==="WARN"?<AlertTriangle className="w-4 h-4 mt-0.5 shrink-0"/>:<Info className="w-4 h-4 mt-0.5 shrink-0"/>}<div><div className="text-sm font-medium">{c.title}</div><div className="text-xs opacity-80 mt-1">{c.detail}</div><div className="text-[11px] opacity-70 mt-2"><span className="font-medium">Resolution:</span> {c.resolution}</div></div></div></div>)}</div>:<div className="rounded-lg border border-[#4ade80]/15 bg-[#4ade80]/5 p-4 text-sm text-[#86efac] flex items-center gap-2"><CheckCircle2 className="w-4 h-4"/>No deterministic compatibility conflicts were found.</div>}</section>
  <div className="rounded-lg border border-white/7 p-4 text-xs text-[#6b7d99] space-y-1">{plan.limitations.map(x=><div key={x}>• {x}</div>)}</div>
 </div>;
}
