import React, { useCallback, useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, FlaskConical, Play, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import type { MarketplaceServiceRecord, MarketplaceServiceTestCoverage, NavState, Route } from "../domain/types";
import { marketplaceSupplyRepository } from "../repositories/marketplaceSupplyRepository";
import { GroundedExplanationPanel } from "./GroundedExplanationPanel";

type Navigate=(route:Route,params?:Partial<NavState>)=>void;
const box="rounded-xl border border-white/8 bg-[#151c28]";
function stateColor(state:string){return state==="PASS"||state==="READY"?"text-[#4ade80]":state==="FAIL"||state==="OFFLINE"||state==="SUSPENDED"?"text-[#f87171]":"text-[#f59e0b]";}

export function LiveAgentProfilePage({serviceId,navigate}:{serviceId:string;navigate:Navigate}){
  const[record,setRecord]=useState<MarketplaceServiceRecord>();const[tests,setTests]=useState<MarketplaceServiceTestCoverage>();const[loading,setLoading]=useState(true);const[error,setError]=useState<string>();
  const load=useCallback(async()=>{setLoading(true);setError(undefined);try{const[r,t]=await Promise.all([marketplaceSupplyRepository.getService(serviceId),marketplaceSupplyRepository.getTests(serviceId)]);setRecord(r);setTests(t);}catch(c){setError(c instanceof Error?c.message:"Spotriq could not load this live service profile.");}finally{setLoading(false);}},[serviceId]);
  useEffect(()=>{void load();},[load]);
  if(loading)return <div className="max-w-4xl mx-auto px-6 py-10 text-sm text-[#6b7d99]"><RefreshCw className="inline w-4 h-4 animate-spin mr-2"/>Loading live AgentService…</div>;
  if(error||!record)return <div className="max-w-4xl mx-auto px-6 py-10"><div className={`${box} p-5 text-sm text-[#f87171]`}>{error??"Service unavailable."}</div></div>;
  const terms=record.offer.terms;
  return <div className="max-w-5xl mx-auto px-6 py-8 space-y-6">
    <button onClick={()=>navigate("explore")} className="text-sm text-[#6b7d99] flex items-center gap-2"><ArrowLeft className="w-4 h-4"/>Back to Explore</button>
    <div><div className="text-[11px] uppercase font-mono tracking-wide text-[#2dd4bf]">Live marketplace service</div><h1 className="text-2xl font-semibold text-[#dde3ef] mt-1">{record.service.name}</h1><p className="text-sm text-[#6b7d99] mt-2 max-w-3xl">{record.service.description}</p></div>
    <div className="grid md:grid-cols-4 gap-3">
      <div className={`${box} p-4`}><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Category</div><div className="text-sm text-[#dde3ef] mt-1">{record.service.category}</div></div>
      <div className={`${box} p-4`}><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Readiness</div><div className={`text-sm mt-1 ${stateColor(record.readiness.state)}`}>{record.readiness.state}</div></div>
      <div className={`${box} p-4`}><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Commercial</div><div className="text-sm text-[#dde3ef] mt-1">{terms?`${terms.commercialModel} · ${terms.serviceType.replaceAll("_"," ")}`:"UNDECLARED"}</div></div>
      <div className={`${box} p-4`}><div className="text-[10px] uppercase font-mono text-[#6b7d99]">Authority</div><div className="text-sm text-[#dde3ef] mt-1">{record.permissionProfile.executionMode}</div></div>
    </div>
    <div className={`${box} p-5`}><div className="flex items-center gap-2 mb-3"><ShieldCheck className="w-4 h-4 text-[#2dd4bf]"/><h2 className="font-medium text-[#dde3ef]">Deterministic readiness</h2></div><div className="space-y-2">{(record.readiness.checks??[]).map(check=><div key={check.code} className="flex items-start justify-between gap-4 border-t border-white/6 pt-2"><div><div className="text-xs text-[#dde3ef]">{check.label}</div><div className="text-[11px] text-[#6b7d99] mt-0.5">{check.detail}</div></div><span className={`text-xs font-mono ${stateColor(check.state)}`}>{check.state}</span></div>)}</div></div>
    <div className={`${box} p-5`}><div className="flex items-center justify-between"><div><h2 className="font-medium text-[#dde3ef]">Marketplace Test Lab</h2><p className="text-xs text-[#6b7d99] mt-1">Live bounded tests; this is separate from external ERC-8004 reputation.</p></div><span className={`text-xs font-mono ${tests?.coverage==="PASS"?"text-[#4ade80]":"text-[#f59e0b]"}`}>{tests?.coverage??"NOT RUN"}</span></div>{tests&&<div className="mt-3 space-y-2">{tests.tests.map(test=><div key={test.testId} className="flex justify-between gap-3 text-xs border-t border-white/6 pt-2"><span className="text-[#9aacc4]">{test.label}</span><span className={stateColor(test.state)}>{test.state}</span></div>)}</div>}</div>
    <GroundedExplanationPanel subjectType="SERVICE" subjectId={serviceId} title="Explain this service" />
    <div className="flex flex-wrap gap-2"><button onClick={()=>navigate("try",{agentId:serviceId})} className="px-4 py-2 rounded-md bg-[#2dd4bf] text-[#07131a] text-sm font-medium flex items-center gap-2"><Play className="w-4 h-4"/>Run Test Lab</button><button onClick={()=>navigate("checkout",{agentId:serviceId})} className="px-4 py-2 rounded-md border border-white/12 text-sm text-[#dde3ef]">Review / Hire</button></div>
    <div className="text-[10px] text-[#52637b]">{record.limitations.join(" ")}</div>
  </div>;
}

export function LiveComparePage({compareIds,navigate}:{compareIds:string[];navigate:Navigate}){
  const[records,setRecords]=useState<MarketplaceServiceRecord[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string>();
  useEffect(()=>{let cancelled=false;setLoading(true);Promise.all(compareIds.slice(0,3).map(id=>marketplaceSupplyRepository.getService(id))).then(v=>{if(!cancelled)setRecords(v);}).catch(c=>{if(!cancelled)setError(c instanceof Error?c.message:"Comparison unavailable.");}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[compareIds]);
  if(loading)return <div className="max-w-5xl mx-auto px-6 py-10 text-sm text-[#6b7d99]">Loading live comparison…</div>;
  return <div className="max-w-6xl mx-auto px-6 py-8 space-y-5"><button onClick={()=>navigate("explore")} className="text-sm text-[#6b7d99] flex items-center gap-2"><ArrowLeft className="w-4 h-4"/>Back</button><div><h1 className="text-2xl font-semibold text-[#dde3ef]">Compare live services</h1><p className="text-sm text-[#6b7d99] mt-1">Only explicit marketplace/readiness/commercial evidence is compared. Missing performance evidence is not converted to zero.</p></div>{error&&<div className="text-sm text-[#f87171]">{error}</div>}{!records.length?<div className={`${box} p-5 text-sm text-[#6b7d99]`}>Select up to three live AgentServices from Explore.</div>:<div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="text-left text-xs text-[#6b7d99] p-3">Field</th>{records.map(r=><th key={r.service.serviceId} className="text-left p-3 border-l border-white/7"><div className="text-[#dde3ef]">{r.service.name}</div><div className="text-[10px] text-[#6b7d99] mt-1">{r.service.category}</div></th>)}</tr></thead><tbody>{[
    ["Readiness",(r:MarketplaceServiceRecord)=>r.readiness.state],
    ["Canonical identity",(r:MarketplaceServiceRecord)=>r.identity.canonicalVerification?.state??"NOT VERIFIED"],
    ["Test Lab",(r:MarketplaceServiceRecord)=>r.readiness.checks.find(c=>c.code==="MARKETPLACE_TESTS")?.state??"UNKNOWN"],
    ["Authority mode",(r:MarketplaceServiceRecord)=>r.permissionProfile.executionMode],
    ["Offer",(r:MarketplaceServiceRecord)=>r.offer.terms?`${r.offer.terms.commercialModel} / ${r.offer.terms.serviceType}`:"UNDECLARED"],
    ["Financial activation",(r:MarketplaceServiceRecord)=>r.service.marketplaceActivationEligible?"ELIGIBLE":"GATED"],
  ].map(([label,get])=><tr key={String(label)} className="border-t border-white/6"><td className="p-3 text-xs text-[#6b7d99]">{String(label)}</td>{records.map(r=><td key={r.service.serviceId} className="p-3 text-sm text-[#9aacc4] border-l border-white/6">{(get as (x:MarketplaceServiceRecord)=>string)(r)}</td>)}</tr>)}</tbody></table></div>}<div className="text-[10px] text-[#52637b]">Spotriq does not declare a universal winner or opaque trust score.</div></div>;
}

export function LiveTryAgentPage({serviceId,navigate}:{serviceId:string;navigate:Navigate}){
  const[record,setRecord]=useState<MarketplaceServiceRecord>();const[tests,setTests]=useState<MarketplaceServiceTestCoverage>();const[running,setRunning]=useState(false);const[error,setError]=useState<string>();
  useEffect(()=>{let cancelled=false;Promise.all([marketplaceSupplyRepository.getService(serviceId),marketplaceSupplyRepository.getTests(serviceId)]).then(([r,t])=>{if(!cancelled){setRecord(r);setTests(t);}}).catch(c=>{if(!cancelled)setError(c instanceof Error?c.message:"Test Lab unavailable.");});return()=>{cancelled=true;};},[serviceId]);
  const run=async()=>{setRunning(true);setError(undefined);try{const result=await marketplaceSupplyRepository.runTests(serviceId);setTests(result.tests);}catch(c){setError(c instanceof Error?c.message:"Marketplace Test Lab could not run this service.");}finally{setRunning(false);}};
  return <div className="max-w-3xl mx-auto px-6 py-8 space-y-5"><button onClick={()=>navigate("agent",{agentId:serviceId})} className="text-sm text-[#6b7d99] flex items-center gap-2"><ArrowLeft className="w-4 h-4"/>Back to service</button><div><div className="text-[11px] uppercase font-mono tracking-wide text-[#2dd4bf]">Marketplace Test Lab</div><h1 className="text-2xl font-semibold text-[#dde3ef] mt-1">Try {record?.service.name??serviceId}</h1><p className="text-sm text-[#6b7d99] mt-1">Runs the bounded live endpoint-policy, reachability, protocol-contract and category-capability tests. It does not move funds or simulate fictional portfolio returns.</p></div>{error&&<div className="text-sm text-[#f87171]">{error}</div>}<div className={`${box} p-5`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><FlaskConical className="w-4 h-4 text-[#2dd4bf]"/><span className="font-medium text-[#dde3ef]">Current coverage</span></div><span className={`text-xs font-mono ${tests?.coverage==="PASS"?"text-[#4ade80]":"text-[#f59e0b]"}`}>{tests?.coverage??"NOT RUN"}</span></div><div className="mt-4 space-y-2">{tests?.tests.map(test=><div key={test.testId} className="flex items-start justify-between gap-4 border-t border-white/6 pt-2"><div><div className="text-xs text-[#dde3ef]">{test.label}</div><div className="text-[11px] text-[#6b7d99] mt-0.5">{test.detail}</div></div>{test.state==="PASS"?<CheckCircle2 className="w-4 h-4 text-[#4ade80] shrink-0"/>:test.state==="FAIL"?<XCircle className="w-4 h-4 text-[#f87171] shrink-0"/>:<span className="text-xs text-[#f59e0b]">{test.state}</span>}</div>)}</div></div><button onClick={()=>void run()} disabled={running} className="px-4 py-2 rounded-md bg-[#2dd4bf] disabled:opacity-50 text-[#07131a] text-sm font-medium flex items-center gap-2">{running?<RefreshCw className="w-4 h-4 animate-spin"/>:<Play className="w-4 h-4"/>}{running?"Running live tests…":"Run bounded live tests"}</button><div className="text-[10px] text-[#52637b]">Test Lab evidence remains distinct from external ERC-8004/8004scan reputation and from financial outcome evidence.</div></div>;
}
