import React,{useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowLeft,ArrowRight,Check,CheckCircle2,Lock,RefreshCw,ShieldCheck,Wallet,X} from "lucide-react";
import type {FinancialExecutionPreflight,NavState,PermissionApprovalMode,PermissionCheckout,PermissionCheckoutCategoryInput,Route,ScopedPermissionRequest,ServiceCategory} from "../domain/types";
import {walletHandlers} from "../services/walletHandlers";
import {commercialRepository} from "../repositories/commercialRepository";
import {marketplaceSupplyRepository} from "../repositories/marketplaceSupplyRepository";
import {permissionCheckoutRepository} from "../repositories/permissionCheckoutRepository";
import {financialExecutionAdapterRepository} from "../repositories/financialExecutionAdapterRepository";
import {GroundedExplanationPanel} from "./GroundedExplanationPanel";
import {AdoptionFeedbackPrompt} from "./AdoptionFeedbackPrompt";
import {adoptionAnalyticsRepository} from "../repositories/adoptionAnalyticsRepository";

const LABEL:Record<ServiceCategory,string>={rebalancing:"Rebalancing",grid:"Grid Trading",yield:"Yield Optimisation",health:"Health Factor Monitoring"};
function button(base:string){return `inline-flex items-center justify-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors disabled:opacity-50 ${base}`;}
function Field({label,value,onChange,placeholder,type="text"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="block"><span className="block text-xs text-[#8090a8] mb-1.5">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-md border border-white/10 bg-[#151d2a] px-3 py-2.5 text-sm text-[#dde3ef] placeholder:text-[#52637b] focus:outline-none focus:border-[#2dd4bf]/40"/></label>}
function Box({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-xl border border-white/8 bg-[#1a2230] p-5 ${className}`}>{children}</div>}

function ExecutionAdapterStatus({preflight}:{preflight?:FinancialExecutionPreflight}){
  if(!preflight)return <div className="mt-4 rounded-md border border-white/8 bg-black/10 p-3 text-xs text-[#6b7d99]">Execution-adapter assessment has not been loaded yet.</div>;
  const failed=preflight.checks.filter(item=>item.blocking&&item.state!=="PASS");
  return <div className="mt-4 rounded-md border border-[#2dd4bf]/15 bg-[#2dd4bf]/5 p-4"><div className="flex items-center justify-between gap-3"><div><div className="text-xs font-mono uppercase text-[#2dd4bf]">v0.26 execution adapter</div><div className="text-sm text-[#dde3ef] mt-1">{preflight.adapter.state} · {preflight.adapter.mode.replaceAll("_"," ")}</div></div><span className={`text-xs font-mono ${preflight.state==="READY_FOR_GUARD"?"text-[#4ade80]":"text-[#f6c66d]"}`}>{preflight.state.replaceAll("_"," ")}</span></div><p className="text-xs text-[#7ea8a3] mt-3">The category adapter can validate exact protocol targets and financial arguments. It does not create a PermissionGrant, signer, transaction, or outcome.</p>{failed.length>0&&<div className="mt-3 space-y-1.5">{failed.map(item=><div key={item.code} className="text-xs text-[#9a8560]"><span className="font-mono text-[#f6c66d]">{item.code}</span> · {item.detail}</div>)}</div>}<div className="mt-3 text-xs text-[#6b7d99]">Execution dispatch: <span className="font-mono text-[#f6c66d]">DISABLED</span></div></div>;
}

export function PermissionCheckoutPage({serviceId,navigate}:{serviceId:string;navigate:(route:Route,params?:Partial<NavState>)=>void}){
  const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState<string>();
  const [record,setRecord]=useState<Awaited<ReturnType<typeof marketplaceSupplyRepository.getService>>>(); const [activationId,setActivationId]=useState<string>(); const [buyer,setBuyer]=useState<string>();
  const [checkout,setCheckout]=useState<PermissionCheckout>(); const [request,setRequest]=useState<ScopedPermissionRequest>(); const [executionPreflight,setExecutionPreflight]=useState<FinancialExecutionPreflight>();
  const [tokenId,setTokenId]=useState(""); const [poolAddress,setPoolAddress]=useState(""); const [assetAddress,setAssetAddress]=useState(""); const [marketAddress,setMarketAddress]=useState("");
  const [primaryLimit,setPrimaryLimit]=useState("200"); const [singleLimit,setSingleLimit]=useState("75"); const [actionCount,setActionCount]=useState("4"); const [triggerHealthFactor,setTriggerHealthFactor]=useState("1.25");
  const [validForMinutes,setValidForMinutes]=useState("60"); const [approvalMode,setApprovalMode]=useState<PermissionApprovalMode>("ASK_BEFORE_EXECUTION"); const [healthRepay,setHealthRepay]=useState(true); const [healthCollateral,setHealthCollateral]=useState(false);
  const category=record?.service.category;
  const steps=["Job","Authority","Limits","Cost","Risk","Review"];
  useEffect(()=>{void adoptionAnalyticsRepository.event("PERMISSION_CHECKOUT_VIEWED",{serviceId,category});},[serviceId,category]);

  const proposedAuthority=useMemo(()=>{
    if(!category)return{can:[],cannot:[]};
    if(category==="rebalancing")return{can:["Manage only the specified PancakeSwap LP position","Use bounded decrease/collect/redeploy actions only through the reviewed execution boundary"],cannot:["Transfer to arbitrary wallets","Use unrelated protocols, routers or blanket approvals"]};
    if(category==="grid")return{can:["Operate only the specified PancakeSwap pool within reviewed capital/action limits"],cannot:["Trade unrelated pools","Move capital to arbitrary wallets","Use an unmodeled trading adapter"]};
    if(category==="yield")return{can:["Allocate only the reviewed asset to explicitly allowed Venus markets within limits"],cannot:["Borrow new assets","Use unrelated protocols or unreviewed markets","Transfer to arbitrary wallets"]};
    return{can:["Repay debt and/or add collateral only when the reviewed health trigger is crossed and within the intervention cap"],cannot:["Borrow more","Withdraw collateral","Use unrelated markets/assets","Transfer to arbitrary wallets"]};
  },[category]);

  async function load(){
    setBusy(true);setError(undefined);
    try{
      const wallet=await walletHandlers.connectWallet();
      const normalizedBuyer=wallet.address.toLowerCase();
      const [service,state]=await Promise.all([marketplaceSupplyRepository.getService(serviceId),commercialRepository.getBuyerState(wallet.address)]);
      const activation=state.activations.find(a=>a.serviceId===serviceId&&a.state==="ACTIVE");
      setRecord(service);setBuyer(normalizedBuyer);setActivationId(activation?.activationId);
      if(activation){
        const prior=await permissionCheckoutRepository.getForActivation(activation.activationId);
        if(prior&&prior.state!=="EXPIRED"&&prior.state!=="CANCELLED"){
          setCheckout(prior);
          if(prior.permissionRequestId){
            try{
              const existingRequest=await permissionCheckoutRepository.getRequest(prior.permissionRequestId);
              setRequest(existingRequest);
              try{setExecutionPreflight(await financialExecutionAdapterRepository.preflight(existingRequest.permissionRequestId,normalizedBuyer));}
              catch{/* adapter assessment is supplementary to the immutable request */}
            }catch{/* request may not exist yet */}
          }
        }
      }
    }catch(cause){setError(cause instanceof Error?cause.message:"Spotriq could not load this permission checkout.");}
    finally{setBusy(false);}
  }

  function scopeInput():PermissionCheckoutCategoryInput{
    if(!category)throw new Error("Service category is unavailable.");
    const actions=Math.max(1,Number.parseInt(actionCount||"0",10)||0);
    if(category==="rebalancing")return{category,positionTokenId:tokenId,token0Limit:primaryLimit,token1Limit:singleLimit,maxActionsPerDay:actions};
    if(category==="grid")return{category,poolAddress,capitalAssetAddress:assetAddress,capitalLimit:primaryLimit,perActionLimit:singleLimit,maxActionsPerDay:actions};
    if(category==="yield")return{category,assetAddress,allowedMarketAddresses:marketAddress?[marketAddress]:[],capitalLimit:primaryLimit,perActionLimit:singleLimit,maxActionsPerDay:actions};
    const protectiveActions:Array<"REPAY"|"ADD_COLLATERAL">=[];if(healthRepay)protectiveActions.push("REPAY");if(healthCollateral)protectiveActions.push("ADD_COLLATERAL");return{category,assetAddress,marketAddresses:marketAddress?[marketAddress]:[],protectiveActions,interventionCap:primaryLimit,triggerHealthFactor,maxInterventionsPerDay:actions};
  }

  async function prepare(){if(!activationId||!buyer)return;setBusy(true);setError(undefined);try{const op=typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${Math.random()}`;const c=await permissionCheckoutRepository.create(activationId,{buyerAddress:buyer,idempotencyKey:`web-permission-checkout:${serviceId}:${op}`,approvalMode,validForMinutes:Number(validForMinutes),scope:scopeInput()});setCheckout(c);setStep(3);}catch(cause){setError(cause instanceof Error?cause.message:"Spotriq could not prepare the permission contract.");}finally{setBusy(false);}}
  async function confirm(){if(!checkout||!buyer)return;setBusy(true);setError(undefined);try{const nextRequest=await permissionCheckoutRepository.confirm(checkout.checkoutId,{buyerAddress:buyer});setRequest(nextRequest);try{setExecutionPreflight(await financialExecutionAdapterRepository.preflight(nextRequest.permissionRequestId,buyer));}catch(cause){setError(cause instanceof Error?`Scope recorded, but execution-adapter assessment failed: ${cause.message}`:"Scope recorded, but execution-adapter assessment could not be loaded.");}}catch(cause){setError(cause instanceof Error?cause.message:"Spotriq could not record the reviewed permission scope.");}finally{setBusy(false);}}

  if(!record)return <div className="max-w-2xl mx-auto px-6 py-12"><button onClick={()=>navigate("agent",{agentId:serviceId})} className="flex items-center gap-2 text-sm text-[#6b7d99] mb-6"><ArrowLeft className="w-4 h-4"/> Back</button><Box><div className="flex items-start gap-3"><Wallet className="w-5 h-5 text-[#2dd4bf] mt-0.5"/><div><h1 className="text-lg font-semibold text-[#dde3ef]">Permission Checkout</h1><p className="text-sm text-[#6b7d99] mt-1">Connect the wallet that owns the Spotriq service relationship. Spotriq will load the real Activation and service PermissionProfile before showing any financial authority review.</p><button className={button("mt-4 bg-[#2dd4bf] text-[#061010]")} onClick={()=>void load()} disabled={busy}>{busy?<RefreshCw className="w-4 h-4 animate-spin"/>:<Wallet className="w-4 h-4"/>}{busy?"Loading":"Connect wallet & load relationship"}</button>{error&&<p className="mt-3 text-xs text-[#fca5a5]">{error}</p>}</div></div></Box></div>;

  if(!activationId)return <div className="max-w-2xl mx-auto px-6 py-12 space-y-5"><button onClick={()=>navigate("agent",{agentId:serviceId})} className="flex items-center gap-2 text-sm text-[#6b7d99]"><ArrowLeft className="w-4 h-4"/> Back</button><Box><div className="flex gap-3"><AlertTriangle className="w-5 h-5 text-[#f59e0b] mt-0.5"/><div><h1 className="text-lg font-semibold text-[#dde3ef]">Active relationship required</h1><p className="text-sm text-[#8090a8] mt-1">Permission Checkout starts from a legitimate Marketplace Activation. Hire and activate the read-only service first; Spotriq will not create financial authority directly from a service card.</p><button className={button("mt-4 border border-[#2dd4bf]/30 text-[#2dd4bf]")} onClick={()=>navigate("explore")}>Return to Explore</button></div></div></Box></div>;

  if(request)return <div className="max-w-2xl mx-auto px-6 py-12 space-y-5"><Box className={request.state==="GRANT_RECONCILED"?"border-[#4ade80]/25":"border-[#f59e0b]/20"}><div className="flex items-start gap-3">{request.state==="GRANT_RECONCILED"?<CheckCircle2 className="w-6 h-6 text-[#4ade80]"/>:<ShieldCheck className="w-6 h-6 text-[#f59e0b]"/>}<div><div className="text-xs font-mono uppercase text-[#6b7d99]">ScopedPermissionRequest</div><h1 className="text-xl font-semibold text-[#dde3ef] mt-1">{request.state==="BLOCKED"?"Scope reviewed — authority not granted":request.state.replaceAll("_"," ")}</h1><p className="text-sm text-[#8090a8] mt-2">This is a separate permission resource. It did not change payment, commercial Activation, execute a transaction, or create a financial outcome.</p><div className="mt-4 rounded-md border border-white/7 bg-black/10 p-3 text-xs font-mono text-[#9aacc4] break-all">{request.permissionRequestId}</div><ExecutionAdapterStatus preflight={executionPreflight}/>{request.blockers.length>0&&<div className="mt-4 space-y-2">{request.blockers.map(b=><div key={b.code} className="rounded-md border border-[#f59e0b]/15 bg-[#f59e0b]/5 p-3"><div className="text-xs font-medium text-[#f6c66d]">{b.label}</div><div className="text-xs text-[#8f7e61] mt-1">{b.detail}</div></div>)}</div>}<div className="mt-4 flex gap-2"><button className={button("border border-white/10 text-[#9aacc4]")} onClick={()=>navigate("explore")}>Explore</button><button className={button("border border-[#2dd4bf]/25 text-[#2dd4bf]")} onClick={()=>navigate("my-agents",{myAgentsTab:"authority"})}>Authority overview</button></div></div></div></Box></div>;

  return <div className="max-w-2xl mx-auto px-6 py-8"><button onClick={()=>navigate("agent",{agentId:serviceId})} className="flex items-center gap-2 text-sm text-[#6b7d99] hover:text-[#9aacc4] mb-6"><ArrowLeft className="w-4 h-4"/> Back</button><div className="mb-6"><div className="text-xs font-mono uppercase text-[#2dd4bf]">Permission Checkout · {LABEL[record.service.category]}</div><h1 className="text-2xl font-semibold text-[#dde3ef] mt-1">Review financial authority separately</h1><p className="text-sm text-[#6b7d99] mt-1">Activation <span className="font-mono">{activationId}</span> is currently read-only. This flow cannot silently upgrade it.</p></div>
    <div className="flex items-center gap-1 mb-8 overflow-x-auto">{steps.map((label,i)=><React.Fragment key={label}><button onClick={()=>i<step&&setStep(i)} className={`shrink-0 rounded px-2.5 py-1.5 text-xs ${i===step?"border border-[#2dd4bf]/30 bg-[#2dd4bf]/10 text-[#2dd4bf]":i<step?"text-[#4ade80]":"text-[#52637b]"}`}>{i<step?<Check className="inline w-3 h-3 mr-1"/>:null}{label}</button>{i<steps.length-1&&<ArrowRight className="w-3 h-3 text-[#293346] shrink-0"/>}</React.Fragment>)}</div>
    {error&&<div className="mb-4 rounded-md border border-[#f87171]/20 bg-[#f87171]/5 p-3 text-xs text-[#fca5a5]">{error}</div>}
    {request&&buyer&&<div className="mb-5"><GroundedExplanationPanel subjectType="PERMISSION_REQUEST" subjectId={request.permissionRequestId} buyerAddress={buyer} title="Explain this authority scope" /></div>}
    {step===0&&<div className="space-y-5"><Box><div className="flex justify-between gap-4"><div><div className="font-semibold text-[#dde3ef]">{record.service.name}</div><div className="text-xs text-[#6b7d99] mt-1">{record.permissionProfile.executionMode} · {record.readiness.state}</div></div><Lock className="w-5 h-5 text-[#6b7d99]"/></div><div className="mt-4 space-y-3">{category==="rebalancing"&&<Field label="PancakeSwap position token ID" value={tokenId} onChange={setTokenId} placeholder="e.g. 12490"/>}{category==="grid"&&<><Field label="PancakeSwap V3 pool address" value={poolAddress} onChange={setPoolAddress} placeholder="0x..."/><Field label="Capital asset address" value={assetAddress} onChange={setAssetAddress} placeholder="0x..."/></>}{category==="yield"&&<><Field label="Asset address" value={assetAddress} onChange={setAssetAddress} placeholder="0x..."/><Field label="Allowed Venus market address (optional)" value={marketAddress} onChange={setMarketAddress} placeholder="0x..."/></>}{category==="health"&&<><Field label="Protective asset address" value={assetAddress} onChange={setAssetAddress} placeholder="0x..."/><Field label="Venus market address (optional)" value={marketAddress} onChange={setMarketAddress} placeholder="0x..."/><div className="flex gap-4 text-sm text-[#9aacc4]"><label><input type="checkbox" checked={healthRepay} onChange={e=>setHealthRepay(e.target.checked)} className="mr-2 accent-[#2dd4bf]"/>Repay</label><label><input type="checkbox" checked={healthCollateral} onChange={e=>setHealthCollateral(e.target.checked)} className="mr-2 accent-[#2dd4bf]"/>Add collateral</label></div></>}</div></Box><button className={button("w-full bg-[#2dd4bf] text-[#061010]")} onClick={()=>setStep(1)}>Continue <ArrowRight className="w-4 h-4"/></button></div>}
    {step===1&&<div className="space-y-5"><Box><div className="text-xs font-mono uppercase text-[#4ade80] mb-3">Proposed bounded authority</div>{proposedAuthority.can.map(v=><div key={v} className="flex gap-2 text-sm text-[#9aacc4] mb-2"><Check className="w-4 h-4 text-[#4ade80] mt-0.5 shrink-0"/>{v}</div>)}<div className="border-t border-white/7 mt-4 pt-4 text-xs font-mono uppercase text-[#6b7d99] mb-3">Explicitly excluded</div>{proposedAuthority.cannot.map(v=><div key={v} className="flex gap-2 text-sm text-[#9aacc4] mb-2"><X className="w-4 h-4 text-[#2dd4bf] mt-0.5 shrink-0"/>{v}</div>)}<p className="text-xs text-[#6b7d99] mt-4">This is a proposed review scope, not evidence the current service can execute it. The server will add deterministic readiness/provider blockers before any PermissionRequest exists.</p></Box><div className="flex gap-2"><button className={button("border border-white/10 text-[#9aacc4]")} onClick={()=>setStep(0)}><ArrowLeft className="w-4 h-4"/></button><button className={button("flex-1 bg-[#2dd4bf] text-[#061010]")} onClick={()=>setStep(2)}>Continue <ArrowRight className="w-4 h-4"/></button></div></div>}
    {step===2&&<div className="space-y-5"><Box className="space-y-4"><Field label={category==="health"?"Maximum protective intervention (asset display amount)":category==="rebalancing"?"Token 0 spend cap (display amount)":"Maximum capital (asset display amount)"} value={primaryLimit} onChange={setPrimaryLimit} type="number"/><Field label={category==="rebalancing"?"Token 1 spend cap (display amount)":category==="health"?"Health-factor trigger":"Maximum single action (display amount)"} value={category==="health"?triggerHealthFactor:singleLimit} onChange={category==="health"?setTriggerHealthFactor:setSingleLimit} type="number"/><Field label={category==="health"?"Maximum interventions per day":"Maximum actions per day"} value={actionCount} onChange={setActionCount} type="number"/><Field label="Authority validity (minutes, 5–1440)" value={validForMinutes} onChange={setValidForMinutes} type="number"/><div><div className="text-xs text-[#8090a8] mb-2">Approval mode</div><div className="space-y-2">{(["ASK_BEFORE_EXECUTION","AUTOMATIC_WITHIN_LIMITS"] as const).map(v=><label key={v} className="flex gap-3 rounded-md border border-white/8 bg-[#151d2a] p-3 text-sm text-[#9aacc4]"><input type="radio" checked={approvalMode===v} onChange={()=>setApprovalMode(v)} className="accent-[#2dd4bf]"/><span>{v==="ASK_BEFORE_EXECUTION"?"Ask before execution":"Automatic within limits"}</span></label>)}</div></div></Box><div className="flex gap-2"><button className={button("border border-white/10 text-[#9aacc4]")} onClick={()=>setStep(1)}><ArrowLeft className="w-4 h-4"/></button><button className={button("flex-1 bg-[#2dd4bf] text-[#061010]")} onClick={()=>void prepare()} disabled={busy}>{busy?<RefreshCw className="w-4 h-4 animate-spin"/>:<ShieldCheck className="w-4 h-4"/>} Build deterministic review</button></div></div>}
    {step===3&&checkout&&<div className="space-y-5"><Box><h2 className="font-semibold text-[#dde3ef]">Cost separation</h2><div className="mt-4 space-y-3 text-sm">{[["Agent fee",checkout.cost.agentFee.value,checkout.cost.agentFee.detail],["Protocol costs",checkout.cost.protocolCosts.value,checkout.cost.protocolCosts.detail],["Gas",checkout.cost.gas.value,checkout.cost.gas.detail],["Performance fee",checkout.cost.performanceFee.value,checkout.cost.performanceFee.detail]].map(([l,v,d])=><div key={l} className="border-b border-white/6 pb-3 last:border-0"><div className="flex justify-between gap-3"><span className="text-[#6b7d99]">{l}</span><span className="text-[#dde3ef] font-mono">{v}</span></div><div className="text-xs text-[#52637b] mt-1">{d}</div></div>)}</div></Box><div className="flex gap-2"><button className={button("border border-white/10 text-[#9aacc4]")} onClick={()=>setStep(2)}><ArrowLeft className="w-4 h-4"/></button><button className={button("flex-1 bg-[#2dd4bf] text-[#061010]")} onClick={()=>setStep(4)}>Continue <ArrowRight className="w-4 h-4"/></button></div></div>}
    {step===4&&checkout&&<div className="space-y-5"><Box><h2 className="font-semibold text-[#dde3ef]">Risk & failure behavior</h2><div className="mt-4 space-y-3 text-sm">{[["Strategy",checkout.risk.strategyRisk],["Protocol",checkout.risk.protocolRisk],["Authority",checkout.risk.authorityRisk],["Failure",checkout.risk.failureBehavior],["Revocation",checkout.risk.revocationBehavior]].map(([l,v])=><div key={l}><div className="text-xs font-mono uppercase text-[#6b7d99]">{l}</div><div className="text-[#9aacc4] mt-1">{v}</div></div>)}</div></Box><div className="flex gap-2"><button className={button("border border-white/10 text-[#9aacc4]")} onClick={()=>setStep(3)}><ArrowLeft className="w-4 h-4"/></button><button className={button("flex-1 bg-[#2dd4bf] text-[#061010]")} onClick={()=>setStep(5)}>I understand <ArrowRight className="w-4 h-4"/></button></div></div>}
    {step===5&&checkout&&<div className="space-y-5"><Box><h2 className="font-semibold text-[#dde3ef]">Review permission contract</h2><p className="text-sm text-[#9aacc4] mt-3">{checkout.reviewSummary}</p><div className="mt-4 grid gap-2 text-xs"><div className="flex justify-between"><span className="text-[#6b7d99]">Scope hash</span><span className="font-mono text-[#8090a8] max-w-[65%] truncate">{checkout.scopeHash}</span></div><div className="flex justify-between"><span className="text-[#6b7d99]">Provider</span><span className="text-[#dde3ef]">{checkout.provider}</span></div><div className="flex justify-between"><span className="text-[#6b7d99]">Submission</span><span className="text-[#dde3ef]">{checkout.providerSubmissionState.replaceAll("_"," ")}</span></div></div>{checkout.blockers.length>0&&<div className="mt-5 space-y-2">{checkout.blockers.map(b=><div key={b.code} className="rounded-md border border-[#f59e0b]/15 bg-[#f59e0b]/5 p-3"><div className="text-xs font-medium text-[#f6c66d]">{b.label}</div><div className="text-xs text-[#8f7e61] mt-1">{b.detail}</div></div>)}</div>}<div className="mt-5 rounded-md border border-[#2dd4bf]/15 bg-[#2dd4bf]/5 p-3 text-xs text-[#7ea8a3]">Recording this review creates a ScopedPermissionRequest only. It does not create a grant, change your read-only Activation, or move funds.</div></Box><div className="flex gap-2"><button className={button("border border-white/10 text-[#9aacc4]")} onClick={()=>setStep(4)}><ArrowLeft className="w-4 h-4"/></button><button className={button("flex-1 bg-[#2dd4bf] text-[#061010]")} onClick={()=>void confirm()} disabled={busy}>{busy?<RefreshCw className="w-4 h-4 animate-spin"/>:<ShieldCheck className="w-4 h-4"/>} Record reviewed scope</button></div></div>}
  </div>;
}
