import test from "node:test";
import assert from "node:assert/strict";
import { cacheControlFor, MemoryDurableWorkQueue, MemoryRateLimitStore, retryDelayMs, stableClientKey } from "./index.js";

test("rate limiting fails closed after bounded allowance",async()=>{const store=new MemoryRateLimitStore();const policy={windowMs:60000,maxRequests:2,keyPrefix:"read"};assert.equal((await store.consume("client",policy)).allowed,true);assert.equal((await store.consume("client",policy)).allowed,true);const third=await store.consume("client",policy);assert.equal(third.allowed,false);assert.equal(third.remaining,0)});
test("durable work enqueue is idempotent and lease ownership is enforced",async()=>{const q=new MemoryDurableWorkQueue();const a=await q.enqueue({kind:"MAINTENANCE",payload:{x:1},idempotencyKey:"one"});const b=await q.enqueue({kind:"MAINTENANCE",payload:{x:1},idempotencyKey:"one"});assert.equal(a.jobId,b.jobId);await assert.rejects(()=>q.enqueue({kind:"MAINTENANCE",payload:{x:999},idempotencyKey:"one"}),/IDEMPOTENCY_CONFLICT/);const leased=await q.claim("w1",30000);assert.equal(leased?.jobId,a.jobId);await assert.rejects(()=>q.complete(a.jobId,"w2"));await q.complete(a.jobId,"w1");assert.equal((await q.stats()).completed,1)});
test("work retries become dead letters at max attempts",async()=>{const q=new MemoryDurableWorkQueue();const item=await q.enqueue({kind:"FAIL",payload:{},idempotencyKey:"fail",maxAttempts:2});let leased=await q.claim("w",1000);assert.ok(leased);await q.fail(item.jobId,"w","first",1000);leased=await q.claim("w",1000);assert.equal(leased,undefined);await new Promise(r=>setTimeout(r,1010));leased=await q.claim("w",1000);assert.ok(leased);const failed=await q.fail(item.jobId,"w","second",1000);assert.equal(failed?.state,"DEAD_LETTER")});
test("cache policy never publicly caches authority/commercial state",()=>{assert.equal(cacheControlFor("GET","/v1/commercial/hire/x"),"private, no-store");assert.equal(cacheControlFor("GET","/v1/activations/a/outcomes"),"private, no-store");assert.equal(cacheControlFor("GET","/v1/checks/check_x"),"private, no-store");assert.match(cacheControlFor("GET","/v1/system/health"),/^public/);assert.equal(cacheControlFor("POST","/v1/checks"),"no-store")});
test("client keys are stable hashes rather than raw addresses",()=>{assert.equal(stableClientKey(" 203.0.113.9 "),stableClientKey("203.0.113.9"));assert.notEqual(stableClientKey("203.0.113.9"),"203.0.113.9")});
test("retry backoff is bounded",()=>{assert.equal(retryDelayMs(1),1000);assert.equal(retryDelayMs(10),60000)});
