import assert from "node:assert/strict";
import test from "node:test";
import type { MarketplaceActivation, MarketplaceServiceRecord } from "@spotriq/domain";
import { createMyAgentsEngine, MemoryMyAgentsStore, MyAgentsError } from "./index.js";

const buyer="0x1111111111111111111111111111111111111111";
function activation(id:string,serviceId:string,state:MarketplaceActivation["state"]="ACTIVE"):MarketplaceActivation{return{activationId:id,hireId:`hire:${id}`,quoteId:`quote:${id}`,serviceId,buyerAddress:buyer,buyerChainId:97,serviceChainId:97,state,activationKind:"READ_ONLY_SERVICE_RELATIONSHIP",termsSnapshot:{termsVersion:"1",commercialModel:"FREE",serviceType:"READ_ONLY_SERVICE",price:{amount:"0",currency:"tBNB"},network:"BSC",chainId:97,paymentRail:"FREE",scope:{summary:"read",protocols:["PancakeSwap"],financialAuthorityRequired:false,walletSigningRequired:false},availability:"AVAILABLE",quoteValiditySeconds:600},termsHash:`hash:${id}`,paymentRequired:false,permissionRequired:false,walletSigningAuthorityGranted:false,financialExecutionAuthorityGranted:false,idempotencyKey:`key:${id}`,activatedAt:"2026-09-01T00:00:00.000Z",updatedAt:"2026-09-01T00:00:00.000Z",methodVersion:"test",evidence:[],limitations:[]};}
function record(serviceId:string,name:string):MarketplaceServiceRecord{return{service:{serviceId,agentId:`agent:${serviceId}`,name,slug:name.toLowerCase(),category:"grid",description:"test",readiness:"TESTNET_ONLY",permissionIntensity:"read-only",pricing:{model:"FREE",amount:"0",protocolCostsNote:"none"},supportedProtocols:["PancakeSwap"],automationMode:"read-only",evidenceSummary:{marketplaceObserved:"tests",testsPassed:4},operator:"Spotriq",erc8004Verified:true,origin:"REFERENCE",marketplaceActivationEligible:false},offer:{offerId:`offer:${serviceId}`,serviceId,state:"AVAILABLE",source:"marketplace-observed",note:"free",terms:{termsVersion:"1",commercialModel:"FREE",serviceType:"READ_ONLY_SERVICE",price:{amount:"0",currency:"tBNB"},network:"BSC",chainId:97,paymentRail:"FREE",scope:{summary:"read",protocols:["PancakeSwap"],financialAuthorityRequired:false,walletSigningRequired:false},availability:"AVAILABLE",quoteValiditySeconds:600}},readiness:{readinessSnapshotId:`ready:${serviceId}`,serviceId,state:"TESTNET_ONLY",checks:[],checkedAt:"2026-09-01T00:00:00.000Z",reasons:[],methodVersion:"test",limitations:[]},permissionProfile:{permissionProfileId:`perm:${serviceId}`,serviceId,executionMode:"READ_ONLY",intensity:"read-only",protocols:["PancakeSwap"],assets:[],provenance:"marketplace-derived"},identity:{} as never,listing:{} as never,capabilityClaims:[],evidence:[],normalizedAt:"2026-09-01T00:00:00.000Z",limitations:[]};}

test("switch activates an eligible same-category replacement before revoking source and is idempotent",async()=>{
  const source=activation("activation:a","svc:a");const replacements=new Map([[source.activationId,source]]);let revoked=false;let activated=0;
  const services=[record("svc:a","A"),record("svc:b","B")];
  const commercial={
    getBuyerState:async()=>({buyerAddress:buyer,quotes:[],hires:[],payments:[],activations:[...replacements.values()],generatedAt:"",methodVersion:"",limitations:[]}),
    getActivation:async(id:string)=>replacements.get(id)!,
    getActivationControl:async(id:string)=>({activationId:id,serviceId:replacements.get(id)!.serviceId,buyerAddress:buyer,category:"grid",activationState:replacements.get(id)!.state,controlTier:"READ_ONLY",runtimeCapability:{code:"ANALYZE_GRID_MARKET",label:"grid",mode:"READ_ONLY",inputRequirements:[]},permissions:{readOnly:[],financialWrite:[],walletSigningAuthorityGranted:false,financialExecutionAuthorityGranted:false},revocable:true,revokeEffect:"",methodVersion:"",limitations:[]}),
    createQuote:async(input:any)=>({quoteId:"q2",offerId:"offer:svc:b",serviceId:input.serviceId,buyerAddress:buyer,buyerChainId:97,state:"OPEN",termsSnapshot:services[1]!.offer.terms!,termsHash:"h",idempotencyKey:input.idempotencyKey,quotedAt:"",expiresAt:"",methodVersion:"",evidence:[],limitations:[]}),
    createHire:async(input:any)=>({hireId:"h2",quoteId:input.quoteId,offerId:"offer:svc:b",serviceId:"svc:b",buyerAddress:buyer,buyerChainId:97,state:"READY_TO_ACTIVATE",termsHash:"h",paymentRequired:false,permissionRequired:false,idempotencyKey:input.idempotencyKey,acceptedAt:"",updatedAt:"",methodVersion:"",limitations:[]}),
    activate:async()=>{activated++;const a=activation("activation:b","svc:b");replacements.set(a.activationId,a);return a;},
    revokeActivation:async(id:string)=>{revoked=true;const a={...replacements.get(id)!,state:"REVOKED" as const};replacements.set(id,a);return a;},
  } as any;
  const engine=createMyAgentsEngine({store:new MemoryMyAgentsStore(),commercial,marketplace:{getService:async(id:string)=>services.find(x=>x.service.serviceId===id)!,listServices:async()=>({services,chainId:56,page:1,limit:100,source:"cache",fetchedAt:"",normalizationMethodVersion:"",limitations:[]})} as any,permissionCheckout:{getForActivation:async()=>undefined} as any,activityOutcomes:{get:async()=>{throw new Error("none")}} as any,now:()=>new Date("2026-09-01T01:00:00.000Z")});
  const first=await engine.switchService({buyerAddress:buyer,sourceActivationId:source.activationId,targetServiceId:"svc:b",idempotencyKey:"switch-1"});
  assert.equal(first.state,"COMPLETED");assert.equal(first.replacementActivationId,"activation:b");assert.equal(activated,1);assert.equal(revoked,true);
  const second=await engine.switchService({buyerAddress:buyer,sourceActivationId:source.activationId,targetServiceId:"svc:b",idempotencyKey:"switch-1"});
  assert.equal(second.switchId,first.switchId);assert.equal(activated,1);
});

test("same-service switch persists BLOCKED and active grant blocks direct relationship ending",async()=>{
  const source=activation("activation:a","svc:a");const service=record("svc:a","A");
  const engine=createMyAgentsEngine({commercial:{getActivation:async()=>source,getBuyerState:async()=>({buyerAddress:buyer,quotes:[],hires:[],payments:[],activations:[source],generatedAt:"",methodVersion:"",limitations:[]}),getActivationControl:async()=>({activationId:source.activationId,serviceId:source.serviceId,buyerAddress:buyer,category:"grid",activationState:"ACTIVE",controlTier:"READ_ONLY",runtimeCapability:{code:"ANALYZE_GRID_MARKET",label:"grid",mode:"READ_ONLY",inputRequirements:[]},permissions:{readOnly:[],financialWrite:[],walletSigningAuthorityGranted:false,financialExecutionAuthorityGranted:false},revocable:true,revokeEffect:"",methodVersion:"",limitations:[]}),revokeActivation:async()=>source} as any,marketplace:{getService:async()=>service,listServices:async()=>({services:[service],chainId:56,page:1,limit:100,source:"cache",fetchedAt:"",normalizationMethodVersion:"",limitations:[]})} as any,permissionCheckout:{getForActivation:async()=>({permissionRequestId:"request:1"}),getRequest:async()=>({state:"GRANT_RECONCILED",permissionGrantId:"grant:1"})} as any,activityOutcomes:{get:async()=>{throw new Error("none")}} as any});
  const blocked=await engine.switchService({buyerAddress:buyer,sourceActivationId:source.activationId,targetServiceId:source.serviceId,idempotencyKey:"same"});
  assert.equal(blocked.state,"BLOCKED");
  await assert.rejects(()=>engine.revokeRelationship({buyerAddress:buyer,activationId:source.activationId}),(error:unknown)=>error instanceof MyAgentsError&&error.code==="ACTIVE_PERMISSION_GRANT");
});
