import assert from "node:assert/strict";
import test from "node:test";
import type { BoundaryFinancialSessionObservation, ControlledRebalancingExecution, FinancialExecutionBoundary, PancakeSwapClPositionSnapshot, RebalancingExecutionPlan, RebalancingJobIntent } from "@spotriq/domain";
import { createActivityOutcomesEngine, MemoryActivityOutcomesStore } from "./index.js";

const receipt={network:"testnet",chainId:97,transactionHash:"0x"+"aa".repeat(32),blockNumber:"12345",blockHash:"0x"+"bb".repeat(32),status:"SUCCESS",gasUsedRaw:"210000",effectiveGasPriceRaw:"3000000000",logs:[]} as import("@spotriq/domain").BscTransactionReceiptSummary;
const execution:ControlledRebalancingExecution={executionId:"exec-1",boundaryId:"boundary-1",planId:"plan-1",planHash:"0xplan",jobIntentId:"job-1",permissionRequestId:"perm-1",financialSessionId:"fs-1",serviceId:"svc-1",walletAddress:"0x1111111111111111111111111111111111111111",network:"testnet",chainId:97,state:"CONFIRMED",calls:[],preflightId:"pf-1",readinessId:"ready-1",sessionVerifiedAt:"2026-08-22T19:50:00.000Z",providerCallsId:"calls-1",providerStatus:"CONFIRMED",transactionHash:receipt.transactionHash,receipt,mintedPositionTokenId:"99",oldPositionLiquidityRawAfter:"0",mintedPositionVerified:true,postStateDetail:"reconciled",createdAt:"2026-08-22T20:00:00.000Z",updatedAt:"2026-08-22T20:01:00.000Z",expiresAt:"2026-08-22T20:05:00.000Z",executionEligible:false,methodVersion:"test",limitations:[]};
const job={jobIntentId:"job-1",state:"COMPLETED",executionState:"CONTROLLED_TESTNET_EXECUTED",category:"rebalancing",checkSessionId:"check",findingId:"finding",walletAddress:execution.walletAddress,walletControl:"VERIFIED_CONTROL",requestedAction:{code:"PREPARE_RANGE_REBALANCE",label:"Rebalance",description:"test"},subject:{protocol:"PancakeSwap",version:"V3",network:"testnet",tokenId:"42",pair:"WBNB/USDT",tickLower:-100,tickUpper:100,currentTick:0,rangeState:"OUT_OF_RANGE_BELOW",blockNumber:"12000"},constraints:{executionMode:"PREPARE_ONLY",maxSlippageBps:50,maxActionCount:4,validForMinutes:30,allowSwapPreparation:false},selectedService:{serviceId:"svc-1",agentId:"agent-1",name:"Range Agent",operator:"operator",matchId:"m1",matchRank:1,matchTier:"EXACT_CONTEXT",readiness:"READY",activationEligible:false,supportedProtocols:["PancakeSwap"],runtimeEndpoints:[]},evidenceReferences:{findingEvidenceIds:[],serviceEvidenceIds:[],readinessEvidenceIds:[]},authority:{state:"GRANT_VERIFIED",requiredBeforeExecution:true,permissionProfileId:"pp-1",declarationState:"DECLARED",walletControl:"VERIFIED_CONTROL",blockers:[]},methodVersion:"test",createdAt:"2026-08-22T19:30:00.000Z",updatedAt:"2026-08-22T20:01:30.000Z",expiresAt:"2026-08-22T21:00:00.000Z",limitations:[]} as RebalancingJobIntent;
const plan={planId:"plan-1",jobIntentId:"job-1",permissionRequestId:"perm-1",serviceId:"svc-1",walletAddress:execution.walletAddress,network:"testnet",chainId:97,state:"REVIEWED",targetRange:{tickLower:-60,tickUpper:60,tickSpacing:10,currentTickAtReview:0,state:"USER_REVIEWED",proposedBy:"USER",reviewedAt:"2026-08-22T19:45:00.000Z",detail:"reviewed"},positionSnapshot:{tokenId:"42",owner:execution.walletAddress,positionManager:"0x2222222222222222222222222222222222222222",token0:{address:"0x3333333333333333333333333333333333333333",symbol:"WBNB",decimals:18,isNative:false},token1:{address:"0x4444444444444444444444444444444444444444",symbol:"USDT",decimals:18,isNative:false},feePips:500,tickLower:-100,tickUpper:100,currentTick:0,tickSpacing:10,liquidityRaw:"1000",recordedTokensOwed0Raw:"0",recordedTokensOwed1Raw:"0",blockNumber:"12000",observedAt:"2026-08-22T19:40:00.000Z"},quote:{quoteId:"q",jobIntentId:"job-1",blockNumber:"12001",observedAt:"2026-08-22T19:44:00.000Z",expiresAt:"2026-08-22T20:10:00.000Z",method:"PANCAKESWAP_V3_ETH_CALL_SIMULATION",liquidityRaw:"1000",expectedDecreaseAmount0Raw:"100",expectedDecreaseAmount1Raw:"200",recordedTokensOwed0Raw:"0",recordedTokensOwed1Raw:"0",expectedCollectAmount0Raw:"100",expectedCollectAmount1Raw:"200",evidenceState:"OBSERVED",limitations:[]},steps:[],planHash:"0xplan",guardState:"PASS",enforcementBoundaryId:"boundary-1",executionEligible:false,createdAt:"2026-08-22T19:40:00.000Z",updatedAt:"2026-08-22T19:45:00.000Z",expiresAt:"2026-08-22T20:10:00.000Z",methodVersion:"test",limitations:[]} as RebalancingExecutionPlan;
const boundary={boundaryId:"boundary-1",planId:"plan-1",jobIntentId:"job-1",permissionRequestId:"perm-1",serviceId:"svc-1",walletAddress:execution.walletAddress,network:"testnet",state:"CONSUMED",planHash:"0xplan",approvedCallHashes:[],approvedStepCount:3,dispatchPolicy:"EXACT_PLAN_CALL_HASH_AND_ORDER",externalAgentRole:"AUTHENTICATED_PROPOSER_ONLY",financialSignerCustody:"BOUNDARY_CONTROLLED_ALTANA_TESTNET_SESSION",financialSessionId:"fs-1",signerProvisioned:true,nonBypassable:true,executionEligible:false,sealedAt:"2026-08-22T19:46:00.000Z",expiresAt:"2026-08-22T20:10:00.000Z",methodVersion:"test",limitations:[]} as FinancialExecutionBoundary;
const session={financialSessionId:"fs-1",boundaryId:"boundary-1",planId:"plan-1",jobIntentId:"job-1",permissionRequestId:"perm-1",serviceId:"svc-1",walletAddress:execution.walletAddress,network:"testnet",chainId:97,provider:"ALTANA",state:"ACTIVE",custody:"SPOTRIQ_BOUNDARY_EPHEMERAL_CLIENT_SIGNER",sessionPublicKey:"0x04"+"11".repeat(64),keyId:"0xkey",requestedCalls:[],grantedCalls:[],requestedSpendCaps:[],grantedSpendCaps:[],expiryUnix:9999999999,expiresAt:"2286-01-01T00:00:00.000Z",reconciliation:"EXACT_MATCH",reconciliationReasons:[],keystoreAddress:"0x5555555555555555555555555555555555555555",onchainValid:true,verifiedAt:"2026-08-22T19:50:00.000Z",verifiedBlockNumber:"12200",exactBoundaryScope:true,distinctFromAgentProposalKey:true,externalAgentHasFinancialSigner:false,signerProvisioned:true,executionEligible:false,methodVersion:"test",limitations:[]} as BoundaryFinancialSessionObservation;
const replacement={protocol:"PancakeSwap",version:"V3",network:"testnet",chainId:97,positionManager:plan.positionSnapshot.positionManager,tokenId:"99",owner:execution.walletAddress,pool:{protocol:"PancakeSwap",version:"V3",network:"testnet",chainId:97,poolAddress:"0x6666666666666666666666666666666666666666",token0:plan.positionSnapshot.token0,token1:plan.positionSnapshot.token1,feePips:500,currentLpFeePips:500,tickSpacing:10,currentTick:0,sqrtPriceX96:"1",liquidityRaw:"5000",currentPriceToken0InToken1:"1",blockNumber:"12345",observedAt:"2026-08-22T20:01:00.000Z",evidence:[]},tickLower:-60,tickUpper:60,liquidityRaw:"900",rangeState:"IN_RANGE",blockNumber:"12345",observedAt:"2026-08-22T20:01:00.000Z",evidence:[],coverage:{ownership:"AVAILABLE",poolState:"AVAILABLE",tokenMetadata:"AVAILABLE",fees:"RECORDED_ONLY",valuation:"NOT_SUPPORTED"}} as PancakeSwapClPositionSnapshot;

function engine(exec=execution, sess=session){const store=new MemoryActivityOutcomesStore();return createActivityOutcomesEngine({store,executions:{async getExecution(){return exec},async getApprovalPlanForBoundary(){return{approvalPlanId:"approval-1",state:"CONFIRMED"}},async getApprovalObservationForPlan(){return{approvalObservationId:"obs-1",approvalPlanId:"approval-1",boundaryId:"boundary-1",walletAddress:execution.walletAddress,provider:"ALTANA",providerStatus:"CONFIRMED",callsId:"approval-calls",state:"CONFIRMED",allowancesSatisfied:true,observedAt:"2026-08-22T19:55:00.000Z",methodVersion:"test",limitations:[]}}},jobs:{async get(){return job}},plans:{async get(){return plan}},boundaries:{async get(){return boundary}},authority:{async getBoundaryFinancialSession(){return sess}},pancakeSwap:{async getV3Position(){return replacement}}});}

test("confirmed execution produces durable activity and immediate outcome evidence",async()=>{const result=await engine().sync("exec-1",new Date("2026-08-22T20:02:00.000Z"));assert.equal(result.outcome?.state,"COLLECTING");assert.equal(result.outcome?.replacementPositionTokenId,"99");assert.equal(result.outcome?.gasCostNativeRaw,"630000000000000");assert.ok(result.activity.some(x=>x.eventType==="EXECUTION_CONFIRMED"));assert.ok(result.activity.some(x=>x.eventType==="BOUNDARY_CONSUMED"));assert.ok(result.activity.some(x=>x.eventType==="JOB_INTENT_COMPLETED"));assert.ok(result.evidence.some(x=>x.metric==="transaction.gas_cost_native"));assert.equal(result.outcome?.performanceMeasurement.state,"INSUFFICIENT_HISTORY");});

test("blocked execution records an activity event but no performance outcome",async()=>{const blocked={...execution,state:"BLOCKED" as const,mintedPositionTokenId:undefined,mintedPositionVerified:false,postStateDetail:"Replacement mint did not reconcile."};const result=await engine(blocked).sync("exec-1");assert.equal(result.outcome,undefined);assert.ok(result.activity.some(x=>x.eventType==="EXECUTION_BLOCKED"));});

test("revoked financial session appears as lifecycle evidence on refresh",async()=>{const revoked={...session,state:"REVOKED" as const,onchainValid:false,signerProvisioned:false,revocationTransactionHash:"0x"+"cc".repeat(32),verifiedAt:"2026-08-22T20:10:00.000Z"};const result=await engine(execution,revoked).sync("exec-1",new Date("2026-08-22T20:11:00.000Z"));assert.ok(result.activity.some(x=>x.eventType==="FINANCIAL_SESSION_REVOKED"));});

test("persisted activity/outcome can be read without recomputing",async()=>{const e=engine();await e.sync("exec-1",new Date("2026-08-22T20:02:00.000Z"));const result=await e.get("exec-1");assert.ok(result.activity.length>0);assert.equal(result.outcome?.replacementPositionTokenId,"99");});
