import test from "node:test";
import assert from "node:assert/strict";
import type { BoundedPermissionRequest, PancakeSwapClPositionSnapshot, RebalancingJobIntent } from "@spotriq/domain";
import type { PancakeSwapReader } from "@spotriq/protocol-pancakeswap";
import { createExecutionPlanEngine, MemoryExecutionPlanStore } from "./index.js";

const wallet="0x1111111111111111111111111111111111111111";
const pm="0x2222222222222222222222222222222222222222";
const token0="0x3333333333333333333333333333333333333333";
const token1="0x4444444444444444444444444444444444444444";
const pool="0x5555555555555555555555555555555555555555";
function job():RebalancingJobIntent{return {jobIntentId:"job-1",state:"AWAITING_AUTHORITY",executionState:"NO_EXECUTION",category:"rebalancing",checkSessionId:"check-1",findingId:"finding-1",walletAddress:wallet,walletControl:"VERIFIED_CONTROL",requestedAction:{code:"PREPARE_RANGE_REBALANCE",label:"Prepare",description:"Prepare"},subject:{protocol:"PancakeSwap",version:"V3",network:"testnet",tokenId:"77",positionManager:pm,token0:{address:token0,symbol:"T0",decimals:18,isNative:false},token1:{address:token1,symbol:"T1",decimals:18,isNative:false},poolAddress:pool,pair:"T0/T1",tickLower:-120,tickUpper:120,currentTick:0,feePips:500,tickSpacing:10,rangeState:"OUT_OF_RANGE_ABOVE",blockNumber:"100"},constraints:{executionMode:"PREPARE_ONLY",maxSlippageBps:50,maxActionCount:4,validForMinutes:30,allowSwapPreparation:false},selectedService:{serviceId:"service-1",agentId:"agent-1",name:"Agent",operator:"Op",matchId:"match-1",matchRank:1,matchTier:"EXACT_CONTEXT",readiness:"LIMITED",activationEligible:false,supportedProtocols:["PancakeSwap"],runtimeEndpoints:[]},evidenceReferences:{findingEvidenceIds:[],serviceEvidenceIds:[],readinessEvidenceIds:[]},authority:{state:"REQUEST_PREPARED",requiredBeforeExecution:true,permissionProfileId:"pp-1",declarationState:"DECLARED",walletControl:"VERIFIED_CONTROL",permissionRequestId:"perm-1",provider:"ALTANA",blockers:[]},methodVersion:"job@1",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+30*60_000).toISOString(),limitations:[]};}
function request():BoundedPermissionRequest{return {permissionRequestId:"perm-1",jobIntentId:"job-1",serviceId:"service-1",walletAddress:wallet,provider:"ALTANA",network:"testnet",chainId:97,protocol:"PancakeSwap",positionManager:pm,tokenId:"77",callAllowlist:[],spendCaps:[{token:token0,decimals:18,limitDisplay:"10",limitRaw:"10000000000000000000",period:"day",provenance:"user-proposed"},{token:token1,decimals:18,limitDisplay:"20",limitRaw:"20000000000000000000",period:"day",provenance:"user-proposed"}],expiresAt:new Date(Date.now()+30*60_000).toISOString(),expiryUnix:Math.floor(Date.now()/1000)+1800,status:"READY",providerSubmissionState:"SAFETY_PREREQUISITES_REQUIRED",safetyPrerequisites:[{code:"TRUSTED_AGENT_SESSION_KEY",state:"SATISFIED",blocking:false,label:"key",detail:"ok",provenance:"marketplace-derived"},{code:"ARGUMENT_LEVEL_EXECUTION_GUARD",state:"REQUIRED",blocking:true,label:"guard",detail:"needed",provenance:"marketplace-derived"},{code:"NON_BYPASSABLE_FINANCIAL_EXECUTION_BOUNDARY",state:"REQUIRED",blocking:true,label:"boundary",detail:"needed",provenance:"marketplace-derived"}],submissionBlockers:[],walletControl:"VERIFIED_CONTROL",scopeProvenance:"marketplace-derived",activationEligible:false,methodVersion:"authority@1",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),limitations:[]};}
function position():PancakeSwapClPositionSnapshot{return {protocol:"PancakeSwap",version:"V3",network:"testnet",chainId:97,positionManager:pm,tokenId:"77",owner:wallet,pool:{protocol:"PancakeSwap",version:"V3",network:"testnet",chainId:97,poolAddress:pool,token0:{address:token0,symbol:"T0",decimals:18,isNative:false},token1:{address:token1,symbol:"T1",decimals:18,isNative:false},feePips:500,tickSpacing:10,currentTick:0,sqrtPriceX96:"1",liquidityRaw:"999",blockNumber:"101",observedAt:new Date().toISOString(),evidence:[]},tickLower:-120,tickUpper:120,liquidityRaw:"1000",rangeState:"IN_RANGE",recordedTokensOwed0Raw:"10",recordedTokensOwed1Raw:"20",blockNumber:"101",observedAt:new Date().toISOString(),evidence:[],coverage:{ownership:"AVAILABLE",poolState:"AVAILABLE",tokenMetadata:"AVAILABLE",fees:"RECORDED_ONLY",valuation:"NOT_SUPPORTED"}};}
function reader():PancakeSwapReader{return {getV3Position:async()=>position(),quoteV3DecreaseLiquidity:async()=>({protocol:"PancakeSwap",version:"V3",network:"testnet",chainId:97,positionManager:pm,tokenId:"77",owner:wallet,liquidityRaw:"1000",expectedAmount0Raw:"1000",expectedAmount1Raw:"2000",recordedTokensOwed0Raw:"10",recordedTokensOwed1Raw:"20",blockNumber:"101",observedAt:new Date().toISOString(),quoteMethod:"ETH_CALL_SIMULATION",limitations:[]})} as unknown as PancakeSwapReader;}

test("prepares a deterministic three-step plan from live position + independent quote",async()=>{const engine=createExecutionPlanEngine({store:new MemoryExecutionPlanStore(),pancakeSwap:reader()});const plan=await engine.prepare(job(),request(),{targetTickLower:-50,targetTickUpper:50});assert.equal(plan.state,"REVIEWABLE");assert.equal(plan.steps.length,3);assert.equal(plan.steps[0].kind,"DECREASE_LIQUIDITY");assert.equal(plan.steps[1].kind,"COLLECT");assert.equal(plan.steps[2].kind,"MINT");assert.equal(plan.quote.expectedCollectAmount0Raw,"1010");assert.equal(plan.guardState,"INCONCLUSIVE");});

test("review refreshes quote and turns the complete plan guard PASS",async()=>{const engine=createExecutionPlanEngine({store:new MemoryExecutionPlanStore(),pancakeSwap:reader()});const draft=await engine.prepare(job(),request(),{targetTickLower:-50,targetTickUpper:50});const reviewed=await engine.review(draft.planId,job(),request());assert.equal(reviewed.state,"REVIEWED");assert.equal(reviewed.targetRange.state,"USER_REVIEWED");assert.equal(reviewed.guardState,"PASS");assert.ok(reviewed.steps.every(s=>s.guard.state==="PASS"));});

test("rejects a replacement range that does not contain the current tick",async()=>{const engine=createExecutionPlanEngine({pancakeSwap:reader()});await assert.rejects(()=>engine.prepare(job(),request(),{targetTickLower:10,targetTickUpper:50}),/must contain/);});
