import test from "node:test";
import assert from "node:assert/strict";
import { AdoptionAnalyticsError, MemoryAdoptionAnalyticsStore, createAdoptionAnalyticsEngine } from "./index.js";

const now=()=>new Date("2026-09-03T00:00:00.000Z");
test("bounded vocabulary hashes session ids and never returns raw identifier",async()=>{const store=new MemoryAdoptionAnalyticsStore();const engine=createAdoptionAnalyticsEngine({store,sessionPepper:"secret",now});const event=await engine.recordEvent({eventName:"HOME_VIEWED",sessionId:"session-123456"});assert.equal(event.eventName,"HOME_VIEWED");assert.notEqual(event.sessionHash,"session-123456");assert.equal(event.sessionHash.length,64);});
test("raw wallet addresses are rejected from browser analytics fields",async()=>{const engine=createAdoptionAnalyticsEngine({store:new MemoryAdoptionAnalyticsStore(),now});await assert.rejects(()=>engine.recordEvent({eventName:"SERVICE_PROFILE_VIEWED",sessionId:"session-123456",subjectId:"0x1111111111111111111111111111111111111111"}),AdoptionAnalyticsError);});
test("acceptance events are excluded from product adoption totals",async()=>{const store=new MemoryAdoptionAnalyticsStore();const engine=createAdoptionAnalyticsEngine({store,now});await engine.recordEvent({eventName:"HOME_VIEWED",sessionId:"product-session",channel:"PRODUCT"});await engine.recordEvent({eventName:"HOME_VIEWED",sessionId:"acceptance-session",channel:"ACCEPTANCE"});const report=await engine.report();assert.equal(report.productEvents,1);assert.equal(report.acceptanceEventsExcluded,1);assert.equal(report.funnel.homeViews,1);});
test("domain facts remain authoritative for lifecycle completion",async()=>{const store=new MemoryAdoptionAnalyticsStore({quotesCreated:4,hiresCreated:3,activationsCreated:2,transactionsObserved:1});const engine=createAdoptionAnalyticsEngine({store,now});await engine.recordEvent({eventName:"HOME_VIEWED",sessionId:"session-123456"});const report=await engine.report();assert.equal(report.funnel.quotesCreated,4);assert.equal(report.funnel.hiresCreated,3);assert.equal(report.funnel.transactionsObserved,1);});
test("Agent Advantage coverage cannot become financial truth",async()=>{const store=new MemoryAdoptionAnalyticsStore({advantageReports:9,advantageMeasured:1});const report=await createAdoptionAnalyticsEngine({store,now}).report();assert.equal(report.funnel.advantageReports,9);assert.equal(report.funnel.advantageMeasured,1);assert.equal(report.authority.agentAdvantage,false);assert.equal(report.authority.outcome,false);});
test("invalid vocabulary and spoofing controls fail closed",async()=>{const engine=createAdoptionAnalyticsEngine({store:new MemoryAdoptionAnalyticsStore(),now});await assert.rejects(()=>engine.recordFeedback({context:"REVOKE",sessionId:"session-123456",comment:"safe\u202Eevil"}),AdoptionAnalyticsError);await assert.rejects(()=>engine.recordEvent({eventName:"NOT_REAL" as never,sessionId:"session-123456"}),AdoptionAnalyticsError);});
